"""
Stock Price Tracker & Notifier
==============================
Tracks stock prices in real-time and sends email/desktop alerts
when prices cross your defined thresholds.
"""

import os
import time
import smtplib
import sqlite3
import logging
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import yfinance as yf
from plyer import notification
from dotenv import load_dotenv

# ── Load environment variables ──────────────────────────────────────────────
load_dotenv()

# ── Logging setup ────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    handlers=[
        logging.FileHandler("tracker.log"),
        logging.StreamHandler(),
    ],
)
log = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════════════
#  DATABASE
# ════════════════════════════════════════════════════════════════════════════

def init_db(path: str = "stocks.db") -> sqlite3.Connection:
    """Create tables if they don't exist and return a connection."""
    conn = sqlite3.connect(path)
    cur = conn.cursor()

    cur.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol      TEXT    NOT NULL,
            alert_type  TEXT    NOT NULL,   -- 'above' | 'below'
            threshold   REAL    NOT NULL,
            active      INTEGER DEFAULT 1,
            created_at  TEXT    DEFAULT (datetime('now'))
        )
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS price_history (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol      TEXT NOT NULL,
            price       REAL NOT NULL,
            recorded_at TEXT DEFAULT (datetime('now'))
        )
    """)

    conn.commit()
    log.info("Database ready at '%s'", path)
    return conn


# ════════════════════════════════════════════════════════════════════════════
#  STOCK DATA
# ════════════════════════════════════════════════════════════════════════════

def get_price(symbol: str) -> float | None:
    """Fetch the latest price for *symbol* via yfinance."""
    try:
        ticker = yf.Ticker(symbol)
        data = ticker.history(period="1d", interval="1m")
        if data.empty:
            log.warning("No data returned for %s", symbol)
            return None
        price = round(float(data["Close"].iloc[-1]), 2)
        log.info("%-6s  $%.2f", symbol, price)
        return price
    except Exception as exc:
        log.error("Error fetching %s: %s", symbol, exc)
        return None


def save_price(conn: sqlite3.Connection, symbol: str, price: float) -> None:
    conn.execute(
        "INSERT INTO price_history (symbol, price) VALUES (?, ?)",
        (symbol, price),
    )
    conn.commit()


# ════════════════════════════════════════════════════════════════════════════
#  NOTIFICATIONS
# ════════════════════════════════════════════════════════════════════════════

def desktop_notify(symbol: str, price: float, threshold: float, kind: str) -> None:
    """Show an OS desktop notification."""
    direction = "↑ ABOVE" if kind == "above" else "↓ BELOW"
    try:
        notification.notify(
            title=f"🚨 Stock Alert – {symbol}",
            message=f"{symbol} is {direction} ${threshold:.2f}\nCurrent price: ${price:.2f}",
            app_name="Stock Tracker",
            timeout=10,
        )
        log.info("Desktop notification sent for %s", symbol)
    except Exception as exc:
        log.warning("Desktop notify failed: %s", exc)


def email_notify(symbol: str, price: float, threshold: float, kind: str) -> None:
    """Send an email alert (configure .env first)."""
    sender    = os.getenv("EMAIL_SENDER")
    password  = os.getenv("EMAIL_PASSWORD")
    recipient = os.getenv("EMAIL_RECIPIENT")
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))

    if not all([sender, password, recipient]):
        log.warning("Email credentials missing – skipping email alert.")
        return

    direction = "above" if kind == "above" else "below"
    subject = f"Stock Alert: {symbol} is {direction} ${threshold:.2f}"

    body = f"""
    <html><body>
    <h2 style="color:#e74c3c;">📈 Stock Price Alert</h2>
    <table>
      <tr><td><b>Symbol</b></td><td>{symbol}</td></tr>
      <tr><td><b>Current Price</b></td><td>${price:.2f}</td></tr>
      <tr><td><b>Threshold</b></td><td>${threshold:.2f} ({direction})</td></tr>
      <tr><td><b>Time</b></td><td>{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</td></tr>
    </table>
    <p>This alert was generated by your Stock Price Tracker.</p>
    </body></html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = sender
    msg["To"]      = recipient
    msg.attach(MIMEText(body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
        log.info("Email alert sent to %s", recipient)
    except Exception as exc:
        log.error("Email send failed: %s", exc)


# ════════════════════════════════════════════════════════════════════════════
#  ALERT MANAGEMENT
# ════════════════════════════════════════════════════════════════════════════

def add_alert(conn: sqlite3.Connection, symbol: str,
              alert_type: str, threshold: float) -> None:
    symbol = symbol.upper()
    conn.execute(
        "INSERT INTO alerts (symbol, alert_type, threshold) VALUES (?, ?, ?)",
        (symbol, alert_type, threshold),
    )
    conn.commit()
    log.info("Alert added: %s %s $%.2f", symbol, alert_type, threshold)


def get_active_alerts(conn: sqlite3.Connection) -> list[dict]:
    cur = conn.execute(
        "SELECT id, symbol, alert_type, threshold FROM alerts WHERE active = 1"
    )
    cols = [c[0] for c in cur.description]
    return [dict(zip(cols, row)) for row in cur.fetchall()]


def deactivate_alert(conn: sqlite3.Connection, alert_id: int) -> None:
    conn.execute("UPDATE alerts SET active = 0 WHERE id = ?", (alert_id,))
    conn.commit()


def check_alerts(conn: sqlite3.Connection, symbol: str, price: float) -> None:
    alerts = [a for a in get_active_alerts(conn) if a["symbol"] == symbol]
    for alert in alerts:
        triggered = (
            (alert["alert_type"] == "above" and price >= alert["threshold"]) or
            (alert["alert_type"] == "below" and price <= alert["threshold"])
        )
        if triggered:
            log.info("🚨 ALERT triggered: %s %s $%.2f (price=$%.2f)",
                     symbol, alert["alert_type"], alert["threshold"], price)
            desktop_notify(symbol, price, alert["threshold"], alert["alert_type"])
            email_notify(symbol, price, alert["threshold"], alert["alert_type"])
            deactivate_alert(conn, alert["id"])


# ════════════════════════════════════════════════════════════════════════════
#  MAIN TRACKER LOOP
# ════════════════════════════════════════════════════════════════════════════

def track(symbols: list[str], interval: int = 60, conn: sqlite3.Connection = None) -> None:
    """
    Poll prices for *symbols* every *interval* seconds.
    Press Ctrl+C to stop.
    """
    if conn is None:
        conn = init_db()

    log.info("Tracking: %s  (interval=%ds)", ", ".join(symbols), interval)
    log.info("Press Ctrl+C to stop.\n")

    try:
        while True:
            print(f"\n{'─'*45}  {datetime.now().strftime('%H:%M:%S')}")
            for sym in symbols:
                price = get_price(sym)
                if price is not None:
                    save_price(conn, sym, price)
                    check_alerts(conn, sym, price)
            time.sleep(interval)
    except KeyboardInterrupt:
        log.info("Tracker stopped by user.")


# ════════════════════════════════════════════════════════════════════════════
#  ENTRY POINT  (quick demo)
# ════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    conn = init_db()

    # ── Add sample alerts (edit to suit your needs) ──────────────────────
    add_alert(conn, "AAPL",  "above", 200.00)   # notify if Apple > $200
    add_alert(conn, "TSLA",  "below", 150.00)   # notify if Tesla < $150
    add_alert(conn, "GOOGL", "above", 180.00)   # notify if Google > $180

    # ── Start tracking ────────────────────────────────────────────────────
    track(
        symbols  = ["AAPL", "TSLA", "GOOGL", "MSFT"],
        interval = 60,       # seconds between each price check
        conn     = conn,
    )
